#!/usr/bin/env python3
"""Generates the support matrix documentation pair from the build's own metadata.

Sources, all machine-readable and already authoritative elsewhere:
  * the version from the root CMakeLists.txt single source,
  * the flat C ABI version from api/wse/capi/wse_capi.h,
  * the binding ABI version from api/wse/binding/Runtime.h,
  * the platform/component/binding surface from the non-hidden CMakePresets.json presets,
  * the pinned dependency identities from bootstrap-manifest.json.

``--check`` regenerates into memory and fails when the committed pair differs, which is the
documentation gate; regenerating the files is the reviewed way to change them. The output embeds
no timestamp so regeneration is deterministic; SYNC_DATE below is bumped when the content changes.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SYNC_DATE = "2026-09-09"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def single(pattern: str, text: str, what: str) -> str:
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"support-matrix source missing: {what}")
    return match.group(1)


def collect(root: Path) -> dict:
    version = single(r'set\(WSE_VERSION "([^"]+)"\)', read(root / "CMakeLists.txt"),
                     "WSE_VERSION in CMakeLists.txt")
    capi_abi = single(r"#define WSE_CAPI_ABI_VERSION (\d+)U",
                      read(root / "api/wse/capi/wse_capi.h"), "WSE_CAPI_ABI_VERSION")
    binding_abi = single(r"BINDING_ABI_VERSION\s*=\s*(\d+)U",
                         read(root / "api/wse/binding/Runtime.h"), "BINDING_ABI_VERSION")

    presets = json.loads(read(root / "CMakePresets.json"))["configurePresets"]
    components = ("xpt", "gef", "iui", "oui", "tmr")
    platforms: dict[str, set] = {}
    for preset in presets:
        if preset.get("hidden"):
            continue
        name = preset["name"]
        if name.startswith("windows-"):
            platform = "Windows x64 (MSVC)"
        elif name.startswith("linux-arm64-"):
            platform = "Linux ARM64 (GCC cross)"
        elif name.startswith("linux-clang-"):
            platform = "Linux x64 (Clang)"
        elif name.startswith("linux-gcc-"):
            platform = "Linux x64 (GCC)"
        else:
            continue
        found = platforms.setdefault(platform, set())
        found.add("core")
        for component in components:
            if re.search(rf"-{component}(-|$)", name) or name.endswith(("-all", "-public")):
                found.add(component)

    manifest = json.loads(read(root / "bootstrap-manifest.json"))
    dependencies = [
        (p["name"], p["version"], p.get("license", "?"))
        for p in manifest["packages"] if p.get("role") == "dependency"
    ]

    return {
        "version": version,
        "capi_abi": capi_abi,
        "binding_abi": binding_abi,
        "platforms": {k: sorted(v) for k, v in sorted(platforms.items())},
        "dependencies": sorted(dependencies),
    }


def platform_table(data: dict, yes: str, no: str) -> list:
    columns = ("core", "xpt", "gef", "iui", "oui", "tmr")
    lines = ["| Platform | " + " | ".join(c.upper() if c != "core" else "Core" for c in columns) + " |",
             "| --- |" + " --- |" * len(columns)]
    for platform, found in data["platforms"].items():
        cells = " | ".join(yes if c in found else no for c in columns)
        lines.append(f"| {platform} | {cells} |")
    return lines


def dependency_table(data: dict) -> list:
    lines = ["| Dependency | Pinned version | License |", "| --- | --- | --- |"]
    lines += [f"| {n} | {v} | {l} |" for n, v, l in data["dependencies"]]
    return lines


def render_en(data: dict) -> str:
    lines = [
        "# WSE Support Matrix",
        "",
        "> Canonical language: English",
        f"> Documentation version: WSE {data['version']}",
        f"> Last synchronized: {SYNC_DATE}",
        "",
        "This page is generated by `tools/release/make_support_matrix.py` from the build's own",
        "metadata - the version source, the ABI headers, the preset catalog, and the bootstrap",
        "manifest - and the `wse.documentation.support_matrix` gate rejects a drift between this",
        "text and those sources. Edit the generator, never this file.",
        "",
        "## Versions and ABI",
        "",
        f"- WSE version: **{data['version']}**",
        f"- Flat C ABI version (`WSE_CAPI_ABI_VERSION`): **{data['capi_abi']}**",
        f"- Binding ABI version (Node/Python/Java): **{data['binding_abi']}**",
        "",
        "## Platforms and components",
        "",
        "A cell records that a maintained CMake preset builds the component on the platform.",
        "Hardware claims are separate: physical validation states live in the",
        "[hardware validation design](../design/en/HardwareValidation.md) and stay",
        "`HARDWARE_NOT_RUN` until device evidence is accepted.",
        "",
    ]
    lines += platform_table(data, "yes", "-")
    lines += [
        "",
        "The access-controlled VPJ component and the language bindings are configure-time options",
        "on top of these presets; the release archives record their exact contents in",
        "`wse-package.json`.",
        "",
        "## Pinned third-party dependencies",
        "",
    ]
    lines += dependency_table(data)
    lines += [""]
    return "\n".join(lines)


def render_ja(data: dict) -> str:
    lines = [
        "# WSE Support Matrix",
        "",
        "> Canonical source: [English WSE Support Matrix](../en/SupportMatrix.md)",
        f"> Documentation version: WSE {data['version']}",
        f"> Last synchronized: {SYNC_DATE}",
        "",
        "本ページは`tools/release/make_support_matrix.py`がBuild自身のMetadata - Version source、",
        "ABI Header、Preset目録、Bootstrap manifest - から生成し、`wse.documentation.support_matrix`",
        "Gateが本文とそれらの乖離を拒否します。編集は生成器に対して行い、本ファイルは編集しません。",
        "",
        "## VersionとABI",
        "",
        f"- WSE version: **{data['version']}**",
        f"- Flat C ABI version（`WSE_CAPI_ABI_VERSION`）: **{data['capi_abi']}**",
        f"- Binding ABI version（Node／Python／Java）: **{data['binding_abi']}**",
        "",
        "## PlatformとComponent",
        "",
        "セルは、維持されているCMake PresetがそのPlatformでComponentをBuildすることを示します。",
        "Hardwareの主張は別勘定です: 実機検証の状態は",
        "[Hardware Validation設計](../design/ja/HardwareValidation.md)にあり、実機Evidenceが",
        "受理されるまで`HARDWARE_NOT_RUN`のままです。",
        "",
    ]
    lines += platform_table(data, "対応", "-")
    lines += [
        "",
        "Access-controlledなVPJ Componentと各言語Bindingは、これらのPresetに重ねるConfigure時",
        "Optionです。Release Archiveの正確な内容は`wse-package.json`が記録します。",
        "",
        "## Pinned third-party dependencies",
        "",
    ]
    lines += dependency_table(data)
    lines += [""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true",
                        help="Fail when the committed pair differs from a regeneration")
    arguments = parser.parse_args()
    root = arguments.source_root.resolve()

    data = collect(root)
    rendered = {
        root / "doc/en/SupportMatrix.md": render_en(data),
        root / "doc/ja/SupportMatrix.md": render_ja(data),
    }

    if arguments.check:
        stale = [str(path.relative_to(root)) for path, text in rendered.items()
                 if not path.is_file() or read(path) != text]
        if stale:
            print("support matrix is stale - regenerate with make_support_matrix.py:\n  "
                  + "\n  ".join(stale), file=sys.stderr)
            return 1
        print("support matrix matches its sources")
        return 0

    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"generated {path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
