# @file verify_deprecation_ledger.cmake
# @brief Verifies that every public deprecation and reviewed OUI opaque alias has a migration record.

if(NOT DEFINED WSE_SOURCE_ROOT OR NOT IS_DIRECTORY "${WSE_SOURCE_ROOT}")
	message(FATAL_ERROR "WSE_SOURCE_ROOT must name the WSE source directory.")
endif()
if(NOT DEFINED WSE_API_ROOT OR NOT IS_DIRECTORY "${WSE_API_ROOT}")
	message(FATAL_ERROR "WSE_API_ROOT must name the public API directory.")
endif()
if(NOT DEFINED WSE_DEPRECATION_LEDGER OR NOT EXISTS "${WSE_DEPRECATION_LEDGER}")
	message(FATAL_ERROR "WSE_DEPRECATION_LEDGER must name the reviewed TSV ledger.")
endif()

file(STRINGS "${WSE_DEPRECATION_LEDGER}" wse_ledger_lines ENCODING UTF-8)
set(wse_ledger_ids)
set(wse_compiler_paths)
set(wse_opaque_alias_paths)
set(wse_compiler_ledger_total 0)
set(wse_opaque_alias_ledger_total 0)

foreach(wse_ledger_line IN LISTS wse_ledger_lines)
	if(wse_ledger_line STREQUAL "" OR wse_ledger_line MATCHES "^[ \t]*#")
		continue()
	endif()
	string(REPLACE "|" ";" wse_ledger_fields "${wse_ledger_line}")
	list(LENGTH wse_ledger_fields wse_ledger_field_count)
	if(NOT wse_ledger_field_count EQUAL 11)
		message(FATAL_ERROR "Invalid deprecation ledger row: ${wse_ledger_line}")
	endif()
	list(GET wse_ledger_fields 0 wse_id)
	list(GET wse_ledger_fields 1 wse_kind)
	list(GET wse_ledger_fields 2 wse_component)
	list(GET wse_ledger_fields 3 wse_header)
	list(GET wse_ledger_fields 4 wse_count)
	list(GET wse_ledger_fields 5 wse_surface)
	list(GET wse_ledger_fields 6 wse_replacement)
	list(GET wse_ledger_fields 7 wse_removal_earliest)
	list(GET wse_ledger_fields 8 wse_ja_migration)
	list(GET wse_ledger_fields 9 wse_en_migration)
	list(GET wse_ledger_fields 10 wse_removal_gate)

	list(FIND wse_ledger_ids "${wse_id}" wse_existing_id_index)
	if(NOT wse_existing_id_index EQUAL -1)
		message(FATAL_ERROR "Duplicate deprecation ledger id: ${wse_id}")
	endif()
	list(APPEND wse_ledger_ids "${wse_id}")
	if(NOT wse_kind MATCHES "^(compiler-deprecated|legacy-opaque-alias)$")
		message(FATAL_ERROR "Unknown deprecation tracking kind for ${wse_id}: ${wse_kind}")
	endif()
	if(wse_component STREQUAL "" OR wse_surface STREQUAL "" OR wse_replacement STREQUAL "")
		message(FATAL_ERROR "Incomplete surface/replacement metadata for ${wse_id}")
	endif()
	if(NOT wse_count MATCHES "^[1-9][0-9]*$")
		message(FATAL_ERROR "Invalid positive count for ${wse_id}: ${wse_count}")
	endif()
	if(NOT wse_removal_earliest STREQUAL "1.0.0")
		message(FATAL_ERROR "Public removal before the approved 1.0.0 floor: ${wse_id}")
	endif()
	if(NOT wse_removal_gate MATCHES
			"^(major-owner-consumers|major-owner-private-consumers|major-owner-hardware-consumers)$")
		message(FATAL_ERROR "Unknown removal gate for ${wse_id}: ${wse_removal_gate}")
	endif()
	if(NOT EXISTS "${WSE_API_ROOT}/${wse_header}")
		message(FATAL_ERROR "Ledger header is missing for ${wse_id}: ${wse_header}")
	endif()

	foreach(wse_migration_reference IN ITEMS "${wse_ja_migration}" "${wse_en_migration}")
		string(FIND "${wse_migration_reference}" "#" wse_anchor_separator)
		if(wse_anchor_separator LESS 1)
			message(FATAL_ERROR "Migration reference lacks a stable anchor: ${wse_migration_reference}")
		endif()
		string(SUBSTRING "${wse_migration_reference}" 0 ${wse_anchor_separator} wse_migration_path)
		math(EXPR wse_anchor_start "${wse_anchor_separator} + 1")
		string(SUBSTRING "${wse_migration_reference}" ${wse_anchor_start} -1 wse_migration_anchor)
		if(NOT EXISTS "${WSE_SOURCE_ROOT}/${wse_migration_path}")
			message(FATAL_ERROR "Migration document is missing: ${wse_migration_path}")
		endif()
		file(READ "${WSE_SOURCE_ROOT}/${wse_migration_path}" wse_migration_text)
		string(FIND "${wse_migration_text}" "<a id=\"${wse_migration_anchor}\"></a>" wse_anchor_index)
		if(wse_anchor_index EQUAL -1)
			message(FATAL_ERROR
				"Migration anchor '${wse_migration_anchor}' is missing from ${wse_migration_path}")
		endif()
	endforeach()

	string(MAKE_C_IDENTIFIER "${wse_kind}_${wse_header}" wse_header_key)
	if(DEFINED wse_expected_${wse_header_key})
		math(EXPR wse_expected_${wse_header_key} "${wse_expected_${wse_header_key}} + ${wse_count}")
	else()
		set(wse_expected_${wse_header_key} "${wse_count}")
	endif()
	if(wse_kind STREQUAL "compiler-deprecated")
		list(APPEND wse_compiler_paths "${wse_header}")
		math(EXPR wse_compiler_ledger_total "${wse_compiler_ledger_total} + ${wse_count}")
	else()
		list(APPEND wse_opaque_alias_paths "${wse_header}")
		math(EXPR wse_opaque_alias_ledger_total "${wse_opaque_alias_ledger_total} + ${wse_count}")
	endif()
endforeach()

list(REMOVE_DUPLICATES wse_compiler_paths)
list(REMOVE_DUPLICATES wse_opaque_alias_paths)
file(GLOB_RECURSE wse_public_headers LIST_DIRECTORIES FALSE
	"${WSE_API_ROOT}/*.h" "${WSE_API_ROOT}/*.hpp")
set(wse_compiler_actual_total 0)
foreach(wse_public_header IN LISTS wse_public_headers)
	file(RELATIVE_PATH wse_relative_header "${WSE_API_ROOT}" "${wse_public_header}")
	string(REPLACE "\\" "/" wse_relative_header "${wse_relative_header}")
	if(wse_relative_header MATCHES "^vpj/")
		continue()
	endif()
	file(READ "${wse_public_header}" wse_header_text)
	string(REGEX MATCHALL "deprecated\\(" wse_deprecated_attributes "${wse_header_text}")
	list(LENGTH wse_deprecated_attributes wse_deprecated_count)
	if(wse_deprecated_count GREATER 0)
		list(FIND wse_compiler_paths "${wse_relative_header}" wse_ledger_path_index)
		if(wse_ledger_path_index EQUAL -1)
			message(FATAL_ERROR "Unregistered public deprecation: ${wse_relative_header}")
		endif()
		string(REGEX REPLACE
			"deprecated\\(\"[^\"]+\"\\)" ""
			wse_undocumented_attributes "${wse_header_text}")
		if(wse_undocumented_attributes MATCHES "deprecated\\(")
			message(FATAL_ERROR "Public deprecation lacks a diagnostic replacement message: ${wse_relative_header}")
		endif()
		math(EXPR wse_compiler_actual_total "${wse_compiler_actual_total} + ${wse_deprecated_count}")
	endif()
endforeach()

foreach(wse_compiler_path IN LISTS wse_compiler_paths)
	file(READ "${WSE_API_ROOT}/${wse_compiler_path}" wse_header_text)
	string(REGEX MATCHALL "deprecated\\(" wse_deprecated_attributes "${wse_header_text}")
	list(LENGTH wse_deprecated_attributes wse_deprecated_count)
	string(MAKE_C_IDENTIFIER "compiler-deprecated_${wse_compiler_path}" wse_header_key)
	if(NOT wse_deprecated_count EQUAL wse_expected_${wse_header_key})
		message(FATAL_ERROR
			"Deprecation count changed for ${wse_compiler_path}: expected ${wse_expected_${wse_header_key}}, "
			"found ${wse_deprecated_count}")
	endif()
endforeach()

foreach(wse_opaque_alias_path IN LISTS wse_opaque_alias_paths)
	file(READ "${WSE_API_ROOT}/${wse_opaque_alias_path}" wse_header_text)
	string(REGEX MATCHALL "void[ \t]*\\*" wse_opaque_aliases "${wse_header_text}")
	list(LENGTH wse_opaque_aliases wse_opaque_alias_count)
	string(MAKE_C_IDENTIFIER "legacy-opaque-alias_${wse_opaque_alias_path}" wse_header_key)
	if(NOT wse_opaque_alias_count EQUAL wse_expected_${wse_header_key})
		message(FATAL_ERROR
			"Legacy opaque alias count changed for ${wse_opaque_alias_path}: expected "
			"${wse_expected_${wse_header_key}}, found ${wse_opaque_alias_count}")
	endif()
endforeach()

if(NOT wse_compiler_actual_total EQUAL wse_compiler_ledger_total)
	message(FATAL_ERROR
		"Public deprecation total changed: ledger ${wse_compiler_ledger_total}, headers ${wse_compiler_actual_total}")
endif()
# The reviewed baseline: zero deprecated declarations and zero legacy opaque aliases. The two
# wse::Map legacy accessors deprecated on 2026-09-08 were removed on 2026-09-13 under the
# pre-publication legacy removal program (doc/deprecation/RemovedApiLedger.tsv). A change to
# either total is a reviewed decision recorded in the ledger and this baseline together, not
# something that appears by accident.
if(NOT wse_compiler_ledger_total EQUAL 0 OR NOT wse_opaque_alias_ledger_total EQUAL 0)
	message(FATAL_ERROR
		"Reviewed deprecation baseline changed: deprecated=${wse_compiler_ledger_total}, "
		"opaque_alias=${wse_opaque_alias_ledger_total}")
endif()

message(STATUS
	"Deprecation ledger passed: ${wse_compiler_ledger_total} compiler deprecations and "
	"${wse_opaque_alias_ledger_total} OUI opaque aliases")
