//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// PF_osDisplayModule_win.rc で使用
//
#define WONDERSTEWENGINE_RSRC_ID_DEFAULT_ICON    101

#define WONDERSTEWENGINE_RSRC_FILENAME_COMMON_TYPE     "CommonType.hlsli"
#define WONDERSTEWENGINE_RSRC_ID_COMMON_TYPE        201
#define WONDERSTEWENGINE_RSRC_ID_WINDOW_PS          202
#define WONDERSTEWENGINE_RSRC_ID_WINDOW_VS          203
#define WONDERSTEWENGINE_RSRC_ID_SCREEN_PS          204
#define WONDERSTEWENGINE_RSRC_ID_SCREEN_VS          205
#define WONDERSTEWENGINE_RSRC_ID_PROJECTION_PS_UP   206
#define WONDERSTEWENGINE_RSRC_ID_PROJECTION_PS_DOWN 207
#define WONDERSTEWENGINE_RSRC_ID_PROJECTION_VS      208


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED

#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif

#endif
